### ISSUE TITLE
[PATCH] Use lib.dir

### ISSUE THREAD

**Issue by GoogleCodeExporter** [relaxng/jing-trang#129]
```
The jing-trang build defines a lib.dir property, but does not use it.  Fix 
attached.
```

Original issue reported on code.google.com by `vsky...@gmail.com` on 28 Nov 2010 at 12:53

Attachments:
- [jing-trang-libdir.patch](https://storage.googleapis.com/google-code-attachments/jing-trang/issue-129/comment-0/jing-trang-libdir.patch)

**Comment by scop** [comment]
#215 is the pull request for this.
