### ISSUE TITLE
[PATCH] Crosslink datatype and regex javadocs with JDK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [relaxng/jing-trang#130]
```
The datatype and regex javadocs are not crosslinked with JDK's docs, fix 
attached.
```

Original issue reported on code.google.com by `vsky...@gmail.com` on 28 Nov 2010 at 2:43

Attachments:
- [jing-trang-javadoc-links.patch](https://storage.googleapis.com/google-code-attachments/jing-trang/issue-130/comment-0/jing-trang-javadoc-links.patch)

**Comment by scop** [comment]
#216 has a pull request for this.
