### ISSUE TITLE
spectest.xml and license

### ISSUE THREAD

**Issue by awalterschulze** [relaxng/jing-trang#199]
I had to go the the old code.google.com site to find the BSD license for this project.
This license did not include an author or a year.
Could you please provide a LICENSE file or have I missed something?

I would like to use the spectest.xml file and open source it another project.
Also on the relaxng.org site the testSuite.zip does not include the spectest.xml file.
The only place I could find it was here.  Thank you Google.

**Comment by awalterschulze** [comment]
Also is their any way I could get the already split spectest.xml file.
It is quite a challenge getting everything installed to run split.xsl and then you still require saxon extensions which seem proprietary.

I got the evaluation saxon ee, and put it in my classpath, but still no luck.
I keep getting
```
saxon.xsl; Line #13; Column #85; org.apache.xml.utils.WrappedRuntimeException: java.lang.NoSuchMethodException: For extension function, could not find method org.apache.xml.dtm.ref.DTMNodeIterator.nodeSet([ExpressionContext,] ).
```

I am running it like so
```
java -cp /usr/share/java/xalan2.jar:./SaxonEE9-6-0-7J/*.jar org.apache.xalan.xslt.Process -xsl split.xsl -in spectest.xml 
```

Please help

**Comment by awalterschulze** [comment]
Ok I think I found a more usable version of the testSuite 
https://github.com/UweSchmidt/hxt/tree/master/hxt-relaxng/examples/RelaxTestSuite

**Comment by sideshowbarker** [comment]
Closing per https://github.com/relaxng/jing-trang/issues/199#issuecomment-147071612
