### ISSUE TITLE
Jing is unable to process XML catalogs with multiple nextCatalog entries

### ISSUE THREAD

**Issue by now** [relaxng/jing-trang#200]
I’m having trouble getting Jing to process an XML catalog with
multiple nextCatalog entries.  If the catalog that contains the
rewrite that I need is located second or anywhere but first among the
nextCatalogs, Jing won’t find it, but if I place it first it works.  I
have traced Jing’s file accesses and it seems that it stops processing
after reading the file referenced in the first nextCatalog.

I’ve looked hard at Catalog.java in the resolver library and at
OasisCatalog.java, but I can’t see anything wrong.

Anyone have an idea of what might be wrong?  I’ll gladly write a
patch, but I’m stumped as to what’s going wrong.

**Comment by now** [comment]
Hi!

OK, so the issue is that we need to override newCatalog in Catalog.  Here’s a patch to do just that:

diff --git a/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java b/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
index 2a8ad94..7242e66 100644
--- a/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
+++ b/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
@@ -51,4 +51,8 @@ class OasisCatalog extends Catalog {
                                     : new ResolverException(e));
     }
   }
+
+  protected Catalog newCatalog() {
+    return new OasisCatalog(catalogManager, saxResolver);
+  }
 }

**Comment by chrispitude** [comment]
> 
> 
> Hi!
> 
> OK, so the issue is that we need to override newCatalog in Catalog. Here’s a patch to do just that:
> 
> ```
> diff --git a/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java b/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
> index 2a8ad94..7242e66 100644
> --- a/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
> +++ b/mod/catalog/src/main/com/thaiopensource/resolver/catalog/OasisCatalog.java
> @@ -51,4 +51,8 @@ class OasisCatalog extends Catalog {
>                                      : new ResolverException(e));
>      }
>    }
> +
> +  protected Catalog newCatalog() {
> +    return new OasisCatalog(catalogManager, saxResolver);
> +  }
>  } 
> ```

I can confirm that your patch resolves this limitation for me too. Let's hope they review and incorporate it soon. Thank you!

**Comment by chrispitude** [comment]
What can we do to get now's patch checked in?

**Comment by sideshowbarker** [comment]
> What can we do to get now's patch checked in?

Create a pull request with the patch

**Comment by sideshowbarker** [comment]
I believe this was wholly fixed by f64bd15. But if that’s not the case, please comment here to say so
