### ISSUE TITLE
brew install jing not working.

### ISSUE THREAD

**Issue by sachinsr099** [relaxng/jing-trang#210]
When I try to install jing in my Mac OS X through Brew, I am getting following error:

==> Downloading https://jing-trang.googlecode.com/files/jing-20091111.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jing"
**Download failed: https://jing-trang.googlecode.com/files/jing-20091111.zip**

Your help is much appreciated.

**Comment by georgebina** [comment]
See https://code.google.com/archive/p/jing-trang/downloads, that file is available at:
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jing-trang/jing-20091111.zip

**Comment by sachinsr099** [comment]
Thanks for responding **georgebina**

Even I found the same link. But  how do I install the same.? How do I make sure it installs in the same way as brew does by coping the dependency files to respective  directories, symlinking etc.

> brew install jing

would have taken care about all this. But as I am getting the error how do I rectify?

I would really appreciate for your help.

**Comment by qiuwei** [comment]
@sachinsr099 

You can simply run
brew edit jing

then replace the oudated url with the one provided by georgebina.
Then run
brew install jing

**Comment by sideshowbarker** [comment]
As far as I can see, there is no current brew package for jing:
```
$ brew install jing
Updating Homebrew...
Error: No available formula with the name "jing"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/jing
To install it, run:
  brew install Caskroom/cask/jing
```

…but that “cask” is from some completely different thing from https://www.techsmith.com/jing.html

**Comment by qiuwei** [comment]
class Jing < Formula
   desc "RELAX NG validator"
   homepage "https://code.google.com/p/jing-trang/"
   url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jing-trang/jing-20091111.zip"
   sha256 "57690280aa6b5521b570aaa5fe77e1b48d84b2a1b0a24da62f9b982c4416908c"

   bottle :unneeded

   def install
     libexec.install Dir["*"]
     bin.write_jar_script libexec/"bin/jing.jar", "jing"
   end
 end

**Comment by paregorios** [comment]
brew reports:

> jing was deleted from homebrew/core in commit 670f3f3a7:
>  jing: migrate to boneyard (https://github.com/Homebrew/homebrew-core/issues/4799)

**Comment by sideshowbarker** [comment]
We’ve never maintained the brew package for jing here, so this isn’t the right place to be having a discussion about it, because there’s nothing we can do here about it anywy

**Comment by sideshowbarker** [comment]
@paregorios Cheers and thanks for adding the update (it reminded me it’s time to just close out the issue here)
