### ISSUE TITLE
Publish new release at GitHub and (Maven) Central Repository

### ISSUE THREAD

**Issue by sideshowbarker** [relaxng/jing-trang#231]
We have enough changes to merit doing and new release here and also to merit publishing new Maven jars at the Central Repository.

So some time within the next two weeks I plan to create a release tag and do that.

As far as the Sonatype Central Repository, the jars will be published under the `io.github.relaxng` groupID — because I don’t have the admin access to either the relaxng.org nor thaiopensource.com domains to be able to prove to Sonatype that I have any association at all with those domains.

**Comment by ndw** [comment]
I think `io.github.relaxng` is fine, but I'll drop a note to @jclark in the hopes of getting his attention. It would be marginally better, I think, to publish them as `org.relaxng.`

And thanks for doing this, @sideshowbarker

**Comment by sideshowbarker** [comment]
Resolved; releases published at:

* https://github.com/relaxng/jing-trang/releases/tag/V20181204
* http://repo1.maven.org/maven2/org/relaxng/
