### ISSUE TITLE
Publish Maven coordinates

### ISSUE THREAD

**Issue by oliviercailloux** [relaxng/jing-trang#250]
It is common practice to include a note with the Maven coordinates (meaning, its group id and artifact id and possibly last published stable version) in some place easy to find, typically, the github README of the project.

See [here](https://github.com/softwaremill/maven-badges) for a nice visual way that has become very common; or [here](https://github.com/google/guava/) for a more verbose example.

Searching for [jing](https://search.maven.org/search?q=jing) on Maven Central may leave some users in doubt about the right official Maven recommended version they should use (at least, I was).

**Comment by oliviercailloux** [comment]
Also, you might want to warn your users about [this](https://github.com/oliviercailloux/java-course/blob/master/HTML%20to%20DOM.adoc#about-dependencies) potential problem with `xml-apis`, which is included as a dependency of `jing`.

**Comment by sideshowbarker** [comment]
Thanks for raising this issue. I think everybody would agree it’d be worthwhile to make the additions detailed in this issue. If you can consider raising pull request with with a patch that makes the changes described, I can make time to review it and merge it. (I think it would otherwise be a while before any of the maintainers could get around to making the changes themselves…)

**Comment by oliviercailloux** [comment]
Can I then switch the README format to Asciidoctor? I am familiar with this format and it is “more standardized” than Markdown…

**Comment by sideshowbarker** [comment]
> Can I then switch the README format to Asciidoctor?

Yeah, a AsciiDoc-formatted `readme.adoc` file rather than the current `readme.md` would be fine

**Comment by oliviercailloux** [comment]
https://github.com/relaxng/jing-trang/pull/251

**Comment by sideshowbarker** [comment]
Merged into master at 05fe5fd.

Thanks much!
