### ISSUE TITLE
[Documents] 404 page not found

### ISSUE THREAD

**Issue by urapico** [relaxng/jing-trang#252]
- https://relaxng.org/jclark/trang-manual.html
- https://relaxng.org/jclark/convert-to-xsd-talk.html

I noticed those pages could be deployed.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. I’ve added the files to the https://github.com/relaxng/relaxng.org repo, so they now show up on the (GitHub Pages) https://relaxng.org/ site.
