### ISSUE TITLE
Why RelaxNG validator reports an error on xmlns attribute?

### ISSUE THREAD

**Issue by angelozerr** [relaxng/jing-trang#272]
I'm starting to integrate Jing in your [XML Language Server](https://github.com/eclipse/lemminx) to provide validation and completion for RelaxNG. I tried this sample: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_lite.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_lite.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Title</title>
      </titleStmt>
      <publicationStmt>
        <p>Publication information</p>
      </publicationStmt>
      <sourceDesc>
        <p>Information about the source</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>Some text here.</p>
    </body>
  </text>
</TEI>
```

that we can found at https://digital-editing.fas.harvard.edu/editor/

And I have an error on `xmlns` attribute:

![image](https://user-images.githubusercontent.com/1932211/194496269-f5e97fba-f2cc-45a7-a9ff-db72646fd41b.png)

Do you think it is a bug from Jing or some Jing configuration which is not done correctly?

**Comment by ndw** [comment]
Are you sure you're parsing with namespace support enabled? What API are you using for parsing? The "attribute" named `xmlns` should not be reported as an attribute if namepace support is enabled.

**Comment by angelozerr** [comment]
Thanks so much @ndw for your comment. I fixed my problem and it was indeed a namespace. I use Xerces SAXParser and my configuration was 

```java
org.apache.xerces.parsers.SAXParser = ...
parser.setFeature("http://xml.org/sax/features/namespace-prefixes", true);
```

I changed to:

```java
org.apache.xerces.parsers.SAXParser = ...
parser.setFeature("http://xml.org/sax/features/namespace-prefixes", false);
```

and now it works pefectly. 

Thanks again @ndw !
