### ISSUE TITLE
Mavenize project and add deploying binary/source/javadocs artifacts to the maven central

### ISSUE THREAD

**Issue by GoogleCodeExporter** [relaxng/jing-trang#98]
```
Here is free (for open-source projects) repository manager hosting and
maven central synchronization:
http://nexus.sonatype.org/oss-repository-hosting.html
```

Original issue reported on code.google.com by `plokhotn...@gmail.com` on 18 Dec 2009 at 1:16

**Comment by SamB** [comment]
@ghostd: Perhaps you should re-create https://github.com/ghostd/jing-trang as a fork of this repository, now that it's here?

**Comment by ghostd** [comment]
Done
